# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
pandoc_version: 1.19.2.1

r:
  - 3.5.1

repos:
  CRAN: https://mran.microsoft.com/snapshot/2018-11-09

install:
  - Rscript scripts/install.R

script:
  - Rscript scripts/cranlogs.R data/cranlogs.txt
  - Rscript scripts/github-views.R data/github-views.txt
